# controller_manager:
#   ros__parameters:
#     update_rate: 1500  # Hz 1500
#     manipulator_joint_trajectory_controller:
#       type: joint_trajectory_controller/JointTrajectoryController
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

# # parameters for each controller listed under controller manager
# manipulator_joint_trajectory_controller:
#   ros__parameters:
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     joints:
#       - elbow_joint
#       - shoulder_lift_joint
#       - shoulder_pan_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
#     state_publish_rate: 100.0
#     action_monitor_rate: 20.0
#     allow_partial_joints_goal: false
#     constraints:
#       stopped_velocity_tolerance: 0.0
#       goal_time: 0.0

# joint_state_broadcaster:
#   ros__parameters:
#     type: joint_state_broadcaster/JointStateBroadcaster

# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1600  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster